/*
-- QUANTIDADE DE CONEXÕES ATUAIS --
DESCRICAO:	ESSE SCRIPT VAI RETORNAR A QUANTIDADE DE CONEXÕES
			SIMULTANEAS DO SEU USUARIO.
            FIQUE ATENTO QUANTO AO LIMITE DEFINIDO
*/
SELECT 
    user, 
    COUNT(*) AS connections
FROM 
    information_schema.processlist
GROUP BY user
ORDER BY connections DESC;
    
-- ####################################################### --

/*
-- GERAR QUERY DE KILL PARA AS CONEXOES --
DESCRICAO:	ESTA QUERY GERA LINHAS DE QUERYS PARA DERRUBAR 
			TODAS AS SUAS SESSOES MENOS A ATUAL.
            RODE A QUERY, COPIE AS QUERYS QUE SERAO GERADAS
            E EXECUTE ELAS.
*/
SELECT 
	CONCAT('KILL ', ID, ';')
FROM 
	information_schema.processlist
WHERE ID <> CONNECTION_ID();

-- ####################################################### --

/*
-- BUSCAR COLUNA POR NOME --
DESCRICAO:	RETORNA TODAS AS TABELAS EM QUE A COLUNA
			BUSCADA ESTA.
*/
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'ID_PESSOA';

-- ####################################################### --

/*
-- LISTAR INFORMACOES SOBRE FKs --
DESCRICAO:	RETORNA TODAS AS CHAVES ESTRANGEIRAS
			DO BANCO E AS TABELAS QUE ELA ESTA RELACIONANDO
*/
SELECT
    kcu.CONSTRAINT_NAME,
    kcu.TABLE_SCHEMA,
    kcu.TABLE_NAME,
    kcu.COLUMN_NAME,
    kcu.REFERENCED_TABLE_SCHEMA,
    kcu.REFERENCED_TABLE_NAME,
    kcu.REFERENCED_COLUMN_NAME,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    ON kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
    AND kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA
WHERE kcu.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY kcu.CONSTRAINT_NAME, kcu.COLUMN_NAME;